const translationStrings = {
    pt: {
        session : "Sessão",
        sessions: "Sessões",
        contact : "Contacto",
        intro1  : "0 + 1 = SOM consiste num ciclo de workshops realizados em contexto escolar, nas escolas primárias do Município de Braga, que visa expor alunos do primeiro ciclo às novas tecnologias aplicadas à arte.",
        intro2  : "Os workshops resultarão em vários jogos e softwares de criação musical originais criados e pensados pelos alunos.",
        session1: "Ritmo",
        session2: "Ritmo e Melodia",
        session3: "Sequenciador",
        session4: "Canção",
        session5: "Notação",
        session6: "Acústica",
        session7: "Teoria",
        soon    : "(disponível brevemente)",
        circleHelp: "Clica nos círculos pequenos para escolher o som - uma vez para o azul, duas vezes para o verde, três vezes para o vermelho, quatro vezes para o branco. Clica nos botões de baixo para escolher o andamento.",
        session4Help: "Clica os números para decidir se o instrumento toca.",
        session5Help: "Clica nas figuras ou nos números para mudar o ritmo.Tenta tocá-lo e, se precisares de ajuda, usa o botão Play. Ajusta a velocidade no controlador à esquerda.",
    },
    en: {
        session: "Session",
        sessions: "Sessions",
        contact: "Contact",
        intro1: "0 + 1 = SOM consists in a series of workshops conducted in school context, in the primary school of the municipality of Braga (in nothern Portugal), that aim to expose the students of age 6 to 10 to the new techonologies applied to art.",
        intro2: "The workshops result in different kind of games and software of musical creation original by the students.",
        session1: "Rhythm",
        session2: "Rhythm and Melody",
        session3: "Sequencer",
        session4: "Song",
        session5: "Notation",
        session6: "Acoustics",
        session7: "Theory",
        soon: "(available soon)",
        circleHelp: "Click the small circles to choose the sound - once for blue, twice for green, three times for red and four times for white. Click the buttons at the bottom to choose the tempo.",
        session4Help: "Click the numbers to decide if the instrument plays.",
        session5Help: "Click the musical figures or the numbers to change the rhythm. Try to play it and, if you need help, use the Play button. Adjust the tempo on the slider to the left.",
    }
}
